name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.25"
          cache: false
      - name: Lint
		uses: golangci/golangci-lint-action@v10
		with:
			version: v2.12.1
